[build]
command = "npm run build"
publish = "dist"

[site]
bucket = "/"
entry-point = "."

[env.production]
name = "production"
route = "*chronocoder.dev/*"

# Specify the Node.js version
NODE_VERSION = "20"